### ISSUE TITLE
Currencies with different number of units after the decimal place

### ISSUE THREAD

**Issue by davvidbaker** [osrec/currencyFormatter.js#19]
According to [ISO 4127](https://en.wikipedia.org/wiki/ISO_4217#Active_codes), some currencies have a different number of decimal places than the usual 2 digits. For instance, the KRW has 0, while the BHD has 3.

Do you have plans to incorporate these quirks into this library/would you be open to a pull request that does so? Thanks!!

**Comment by osrec** [comment]
Thanks for the pull request - we will get this merged in a few days - just clearing a backlog of issues!

**Comment by osrec** [comment]
Just reviewed your pull request, and I'm thinking it might be easier to just maintain a custom set of locales that we map against these currencies, rather than adding all the logic with the mantissa length.

What do you think?

**Comment by davvidbaker** [comment]
Yeah maybe. I think the more important thing is that the mantissa should be a function of countryCode and not locale, but maybe that isn't something you want this library to do.

**Comment by osrec** [comment]
Ok, we have another swerve ball. Spoke to the original creator of the lib, and it turns out that the locale should indeed drive the currency format, not the currency itself. Why? Because one currency can be formatted differently across different regions (classic example is the Euro). ISO 4217 lists the currencies and the minor units, but not the formats. The standard for currency formats is the CLDR (http://cldr.unicode.org/), which is what the library is based on, however the CLDR can take a bit of time to update. 

So we will close this pull request for now, but you did make some important format updates to a number of currencies, which we will include in the next update. Thanks for all the hard work :)
